context:
  version: 1.0.0

package:
  name: zet
  version: ${{ version }}

source:
  url: https://github.com/yarrow/zet/archive/v${{ version }}.tar.gz
  sha256: 792a1a1de73bf4145ccaa71f8e6bb34b62e690270a432c4de4d8639e1a741b5b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - zet --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: CLI utility to find the union, intersection, and set difference of files
  homepage: https://github.com/yarrow/zet
  repository: https://github.com/yarrow/zet

extra:
  recipe-maintainers:
    - danielnachun
